#!/usr/bin/bash

# Update system
sudo pamac upgrade -a && sudo pkgfile -u

#General Apps
sudo pacman -Syu firefox chromium gnome-system-monitor gnome-disk-utility virtualbox krita gimp

#Important systems apps
sudo pacman -Syu timeshift tlp firejail

# Installing snapd
sudo pacman -Syu snapd
sudo systemctl enable --now snapd.socket

# Snapd apps
sudo snap install code --classic

# Development tech
sudo pacman -Syu base-devel

# Javascript
sudo pacman -Syu nodejs

# Java
sudo pacman -Syu jdk-openjdk openjdk-src jre-openjdk openjdk-doc

# Ruby
sudo pacman -Syu ruby rubygems
gem install bundler
