#!/usr/bin/bash

# Update system
sudo pamac upgrade -a && sudo pkgfile -u

# General Apps
sudo pacman -Syu firefox
sudo pacman -Syu chromium
sudo pacman -Syu gnome-system-monitor
sudo pacman -Syu gnome-disk-utility
sudo pacman -Syu virtualbox
sudo pacman -Syu krita
sudo pacman -Syu gimp
sudo pacman -Syu timeshift

# Installing snapd
sudo pacman -Syu snapd
sudo systemctl enable --now snapd.socket

# Snapd apps
sudo snap install code --classic

# Development tech
sudo pacman -Syu base-devel

# Javascript
sudo pacman -Syu nodejs

# Java
sudo pacman -Syu jdk-openjdk
sudo pacman -Syu jre-openjdk
sudo pacman -Syu openjdk-doc
sudo pacman -Syu openjdk-src



